services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: dev_frontend
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev -- --host
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true
      VITE_API_URL: http://localhost:3000
    networks:
      - gsc

networks:
  gsc:
    external: true
